name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Bump git-for-windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/git-for-windows/git/releases/download/v2.47.0.windows.2/Git-2.47.0.2-64-bit.exe" -OutFile "${{runner.temp}}/git-for-windows.exe"
          Start-Process -Filepath "${{runner.temp}}/git-for-windows.exe" -ArgumentList  @("/VERYSILENT","/NORESTART","/NOCANCEL","/SP-","/CLOSEAPPLICATIONS","/RESTARTAPPLICATIONS","/o:PathOption=CmdTools","/o:BashTerminalOption=ConHost","/o:EnableSymlinks=Enabled","/COMPONENTS=gitlfs") -NoNewWindow -Wait  

      - uses: actions/checkout@v4

      ## Install SSH Windows
      - uses: shimataro/ssh-key-action@v2
        with:
          key: "${{ secrets.NATHAN_SSH }}"
          name: id_rsa
          known_hosts: "git@github.com"
          if_key_exists: fail

      - name: Confirm SSH AUTH
        run: ssh -T git@github.com
        shell: bash
        continue-on-error: true

      - name: Test Clone Public Repo
        run: git clone --depth 1 git@github.com:octocat/Hello-World.git
        shell: bash

      - name: Test Clone Public Repo
        run: git clone --depth 1 git@github.com:pieces-app/cli-agent.git
        shell: bash

      - name: Test Clone Internal Repo
        run: git clone --depth 1 git@github.com:nathan-courtney-pieces/flutter_test_windows_runner.git
        shell: bash
