name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      ## Install SSH Windows
      - uses: shimataro/ssh-key-action@v2
        with:
          key: "${{ secrets.NATHAN_SSH }}"
          name: id_rsa
          known_hosts: "git@github.com"
          if_key_exists: fail

      - name: Confirm SSH AUTH
        run: ssh -T git@github.com
        shell: bash
        continue-on-error: true

      - name: Test Clone Public Repo
        run: git clone --depth 1 git@github.com:octocat/Hello-World.git
        shell: bash

      - name: Test Clone Public Repo
        run: git clone --depth 1 git@github.com:pieces-app/cli-agent.git
        shell: bash

      - name: Test Clone Internal Repo
        run: git clone --depth 1 git@github.com:nathan-courtney-pieces/flutter_test_windows_runner.git
        shell: bash
